# Generated by Django 5.2.3 on 2025-06-18 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Calender', '0002_availability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted'), ('inherit', 'Inherit')], default='public', max_length=100)),
                ('availability_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Calender.availability')),
                ('conflict_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Calender.conflictcalendar')),
                ('event_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Calender.calendar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'db_table': 'event_type',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLocations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[('in_person', 'In-person'), ('call', 'Call')], max_length=100)),
                ('location_data', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', related_query_name='ls', to='EventType.eventtype')),
            ],
            options={
                'verbose_name': 'Event Locations',
                'verbose_name_plural': 'Event Locations',
                'db_table': 'event_locations',
                'ordering': ['event_type', 'location_type'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('event_type',), name='unique_default_location_per_event_type')],
            },
        ),
        migrations.CreateModel(
            name='EventTypeDurations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('is_default', models.BooleanField(default=False)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', related_query_name='ds', to='EventType.eventtype')),
            ],
            options={
                'verbose_name': 'Event Type Durations',
                'verbose_name_plural': 'Event Type Durations',
                'db_table': 'event_type_duration',
                'ordering': ['-event_type', 'is_default', 'duration'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('event_type',), name='unique_default_duration_per_event_type')],
            },
        ),
    ]
