# Generated by Django 5.2.3 on 2025-06-20 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventType', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeLocations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[('in_person', 'In-person'), ('call', 'Call')], max_length=100)),
                ('location_data', models.JSONField(blank=True, default=dict, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', related_query_name='ls', to='EventType.eventtype')),
            ],
            options={
                'verbose_name': 'Event Locations',
                'verbose_name_plural': 'Event Locations',
                'db_table': 'event_type_locations',
                'ordering': ['event_type', 'location_type'],
            },
        ),
        migrations.DeleteModel(
            name='EventLocations',
        ),
        migrations.AddConstraint(
            model_name='eventtypelocations',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('event_type',), name='unique_default_location_per_event_type'),
        ),
    ]
