# Generated by Django 5.2.3 on 2025-06-21 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventType', '0002_eventtypelocations_delete_eventlocations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='page_slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventtype',
            unique_together={('owner', 'page_slug')},
        ),
    ]
