# Generated by Django 5.2.3 on 2025-06-21 15:58

from django.db import migrations
from django.utils.text import slugify


def populate_event_type_slugs(apps, schema_editor):
    EventType = apps.get_model('EventType', 'EventType')
    db_alias = schema_editor.connection.alias

    for event_type in EventType.objects.using(db_alias).all():
        if not event_type.page_slug:
            base_slug = slugify(event_type.name)
            generated_slug = base_slug
            counter = 1

            while EventType.objects.using(db_alias).filter(
                    owner=event_type.owner, page_slug=generated_slug
            ).exclude(pk=event_type.pk).exists():
                generated_slug = f"{base_slug}-{counter}"
                counter += 1
            event_type.page_slug = generated_slug
            event_type.save(update_fields=['page_slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('EventType', '0003_eventtype_page_slug_alter_eventtype_unique_together'),
    ]

    operations = [
        migrations.RunPython(populate_event_type_slugs, migrations.RunPython.noop),
    ]
