# Generated by Django 5.2.3 on 2025-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventType', '0004_auto_20250621_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypelocations',
            name='location_type',
            field=models.CharField(choices=[('in-person', 'In-person'), ('call', 'Call')], max_length=100),
        ),
    ]
