# Generated by Django 5.2.3 on 2025-06-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventType', '0005_alter_eventtypelocations_location_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtypedurations',
            options={'ordering': ['-event_type', '-is_default', 'duration'], 'verbose_name': 'Event Type Durations', 'verbose_name_plural': 'Event Type Durations'},
        ),
        migrations.AlterModelOptions(
            name='eventtypelocations',
            options={'ordering': ['-event_type', '-is_default', 'location_type'], 'verbose_name': 'Event Locations', 'verbose_name_plural': 'Event Locations'},
        ),
    ]
