# Generated by Django 5.2.3 on 2025-06-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventType', '0006_alter_eventtypedurations_options_and_more'),
        ('MultiEventType', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='multi_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='MultiEventType.multieventtype'),
        ),
    ]
