# Generated by Django 5.2.3 on 2025-06-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventType', '0007_eventtype_multi_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='multi_event',
        ),
    ]
