# Generated by Django 5.2.3 on 2025-07-17 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], db_index=True, max_length=10)),
                ('path', models.TextField()),
                ('status_code', models.IntegerField(choices=[(200, '200 OK'), (201, '201 Created'), (202, '202 Accepted'), (204, '204 No Content'), (301, '301 Moved Permanently'), (302, '302 Found'), (304, '304 Not Modified'), (400, '400 Bad Request'), (401, '401 Unauthorized'), (403, '403 Forbidden'), (404, '404 Not Found'), (405, '405 Method Not Allowed'), (409, '409 Conflict'), (410, '410 Gone'), (415, '415 Unsupported Media Type'), (422, '422 Unprocessable Entity'), (429, '429 Too Many Requests'), (500, '500 Internal Server Error'), (502, '502 Bad Gateway'), (503, '503 Service Unavailable'), (504, '504 Gateway Timeout')], db_index=True)),
                ('duration', models.DurationField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'db_table': 'api_request_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_request_timesta_df69e7_idx'), models.Index(fields=['status_code'], name='api_request_status__5b8a12_idx'), models.Index(fields=['method'], name='api_request_method_8b5f63_idx'), models.Index(fields=['remote_ip'], name='api_request_remote__b9da3e_idx'), models.Index(fields=['user'], name='api_request_user_id_cbf24e_idx')],
            },
        ),
    ]
