# Generated by Django 5.2.3 on 2025-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='error_trace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
