# Generated by Django 5.2.3 on 2025-07-02 17:31

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventType', '0006_alter_eventtypedurations_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiEventConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0)),
                ('buffer_before', models.DurationField(default=datetime.timedelta(0))),
                ('event_type', models.OneToOneField(limit_choices_to={'visibility': 'inherit'}, on_delete=django.db.models.deletion.CASCADE, related_name='multi_event_connection', to='EventType.eventtype')),
            ],
            options={
                'verbose_name': 'Multi Event Connection',
                'verbose_name_plural': 'Multi Event Connections',
                'db_table': 'multi_events_connection',
                'ordering': ['multi_event_type', 'position'],
            },
        ),
        migrations.CreateModel(
            name='MultiEventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=100)),
                ('page_slug', models.SlugField(max_length=255, null=True)),
                ('event_types', models.ManyToManyField(blank=True, help_text='Events associated with this multi-event type.', related_name='multi_event', through='MultiEventType.MultiEventConnection', to='EventType.eventtype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multi Event Type',
                'verbose_name_plural': 'Multi Event Types',
                'db_table': 'multi_event_type',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='multieventconnection',
            name='multi_event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_type_connections', related_query_name='connection', to='MultiEventType.multieventtype'),
        ),
        migrations.AlterUniqueTogether(
            name='multieventconnection',
            unique_together={('multi_event_type', 'event_type'), ('multi_event_type', 'position')},
        ),
    ]
