# Generated by Django 5.2.3 on 2025-06-29 16:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventType', '0008_remove_eventtype_multi_event'),
        ('MultiEventType', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multieventtype',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='Events associated with this multi-event type.', related_name='multi_event', to='EventType.eventtype'),
        ),
        migrations.AddField(
            model_name='multieventtype',
            name='page_slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MultiEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('buffer_before', models.DurationField(default=datetime.timedelta(0))),
                ('event_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EventType.eventtype')),
                ('multi_event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MultiEventType.multieventtype')),
            ],
            options={
                'verbose_name': 'Multi Event Connection',
                'verbose_name_plural': 'Multi Event Connections',
                'db_table': 'multi_events_connection',
                'ordering': ['multi_event_type', 'position'],
                'unique_together': {('multi_event_type', 'event_type')},
            },
        ),
    ]
