# Generated by Django 5.2.3 on 2025-06-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiEventType', '0002_multieventtype_events_multieventtype_page_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multieventtype',
            old_name='events',
            new_name='event_types',
        ),
        migrations.AlterField(
            model_name='multievents',
            name='multi_event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_type_connections', related_query_name='connection', to='MultiEventType.multieventtype'),
        ),
    ]
