# Generated by Django 5.2.1 on 2025-06-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setup_progress',
            field=models.SmallIntegerField(choices=[(0, 'Connect Accounts'), (1, 'Event Calendar'), (2, 'Conflict Calendar'), (3, 'Availability Calendar'), (4, 'Completed')], default=0),
        ),
    ]
