# Generated by Django 5.2.3 on 2025-06-18 15:59

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_setup_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(use_pytz=True),
        ),
    ]
