# Generated by Django 5.2.1 on 2025-05-20 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('provider', models.CharField(choices=[('Google', 'Google'), ('Microsoft', 'Microsoft')], max_length=100)),
                ('connected_on', models.DateTimeField(auto_now_add=True)),
                ('refresh_token', models.CharField(blank=True, max_length=250, null=True)),
                ('refresh_token_expires', models.DateTimeField(blank=True, null=True)),
                ('unique_id', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calenders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calender',
                'verbose_name_plural': 'Calenders',
                'db_table': 'calender_accounts',
            },
        ),
    ]
