# Generated by Django 5.2.1 on 2025-05-24 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('provider', models.CharField(choices=[('Google', 'Google'), ('Microsoft', 'Microsoft')], max_length=100)),
                ('connected_on', models.DateTimeField(auto_now_add=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('refresh_token_expires', models.DateTimeField(blank=True, null=True)),
                ('unique_id', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calenders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Account',
                'verbose_name_plural': 'Calendar Accounts',
                'db_table': 'calendar_accounts',
            },
        ),
        migrations.CreateModel(
            name='CalendarFetch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('sync_token', models.CharField(blank=True, max_length=250)),
                ('total_pages', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='started', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetches', to='Calender.calendaraccount')),
            ],
            options={
                'verbose_name': 'Calendar Fetch',
                'verbose_name_plural': 'Calendar Fetches',
                'db_table': 'calendars_fetch',
                'ordering': ['-started_on'],
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('provider_id', models.CharField(blank=True, max_length=250)),
                ('access', models.CharField(choices=[('reader', 'Reader'), ('writer', 'Writer')], max_length=100)),
                ('primary', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='Calender.calendaraccount')),
                ('last_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated', to='Calender.calendarfetch')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
                'db_table': 'calendars',
                'ordering': ['-primary', '-access', '-added_on'],
            },
        ),
        migrations.CreateModel(
            name='UserCalendarSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_event_calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_event_calendar', to='Calender.calendar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Calendar Settings',
                'verbose_name_plural': 'User Calendar Settings',
                'db_table': 'user_calendar_settings',
            },
        ),
    ]
