# Generated by Django 5.2.1 on 2025-05-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaraccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
