# Generated by Django 5.2.1 on 2025-06-06 17:45

import Calender.utils
import django.db.models.deletion
import timezone_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('weekly_availability', models.JSONField(default=Calender.utils.week_availability_default)),
                ('individual_days_availability', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'db_table': 'availability',
                'ordering': ['-user'],
            },
        ),
        migrations.AddField(
            model_name='usercalendarsettings',
            name='default_availability_calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_availability_calendar', to='Calender.availability'),
        ),
        migrations.CreateModel(
            name='ConflictCalendarGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_calendars_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conflict Calendar Group',
                'verbose_name_plural': 'Conflict Calendar Groups',
                'db_table': 'conflict_calendars_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usercalendarsettings',
            name='default_conflict_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_conflict_group', to='Calender.conflictcalendargroup'),
        ),
        migrations.CreateModel(
            name='ConflictCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_calendars', to='Calender.calendar')),
                ('calendar_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_calendars', to='Calender.conflictcalendargroup')),
            ],
            options={
                'verbose_name': 'Conflict Calendar',
                'verbose_name_plural': 'Conflict Calendars',
                'db_table': 'conflict_calendars',
                'unique_together': {('calendar', 'calendar_group')},
            },
        ),
    ]
