# Generated by Django 5.2.1 on 2025-05-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calender', '0002_alter_calendaraccount_refresh_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendaraccount',
            options={'verbose_name': 'Calendar', 'verbose_name_plural': 'Calendars'},
        ),
        migrations.AlterModelTable(
            name='calendaraccount',
            table='calendar_accounts',
        ),
    ]
